version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: semver-gen
    main: .
    binary: semver-generator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.PKG_VERSION={{.Version}}

archives:
  - id: semver-gen
    formats: [tar.gz]
    name_template: "semver-generator-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md
      - config.yaml

checksum:
  name_template: "semver-generator-checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge'
      - '^WIP'
      - '^Update go.mod'

release:
  github:
    owner: lukaszraczylo
    name: semver-generator
  name_template: "version {{.Version}}"
  draft: false
  prerelease: auto

dockers_v2:
  - images:
      - "ghcr.io/lukaszraczylo/semver-generator"
    tags:
      - "{{ .Version }}"
      - "latest"
      - "v1"
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - config-release.yaml
      - entrypoint.sh

homebrew_casks:
  - name: semver-generator
    repository:
      owner: lukaszraczylo
      name: homebrew-taps
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: https://github.com/lukaszraczylo/semver-generator
    description: "Automatic semantic version generator based on git commit messages"
    license: MIT
    url:
      verified: github.com/lukaszraczylo/semver-generator
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr",
                           args: ["-dr", "com.apple.quarantine", "#{staged_path}/semver-generator"]
          end
