# action.yml
name: 'Semantic Version Generator'
description: 'Automagic semantic version generator'
author: Lukasz Raczylo
branding:
  icon: chevron-right
  color: gray-dark
inputs:
  config_file:
    description: 'Configuration file'
    required: false
  repository_url:
    description: 'Repository URL'
    required: false
    default: 'https://github.com/lukaszraczylo/simple-gql-client'
  repository_local:
    description: 'Use already cloned repository in current directory'
    required: false
outputs:
  semantic_version:
    description: 'Calculated semantic version'
runs:
  using: 'docker'
  image: ./Dockerfile-action
